ports:
  driven:
    timeseries:
      source: cassandra

      postgres:
        url: jdbc:postgresql://localhost:5432/postgres
        username: test
        password: test
        driver-class-name: org.postgresql.Driver
      cassandra:
        local-datacenter: datacenter1
        keyspace-name: my_keyspace